---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by CriticalRR.
--- Copyright (c) CriticalRR - All Rights Reserved
--- DateTime: 05/04/2023 04:20
---

fx_version "cerulean"
game "gta5"
lua54 "yes"

name 'fivem-maintenance'
author 'CriticalRR'
contact 'CriticalR#0563'
repository 'https://github.com/CriticalRR/fivem-maintenance'
discord 'https://discord.gg/kcgKxtHgCf'
description 'This Lua script for FiveM allows you to set up a maintenance system for your server. '

server_scripts {
    "server/sv_maintenance.lua"
}
