---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MiraxxR.
--- Copyright (c) MiraxxR - All Rights Reserved
--- DateTime: 05/04/2023 04:20
---

fx_version "cerulean"
game "gta5"
lua54 "yes"

name 'fivem-maintenance'
author 'MiraxxR'
contact 'MiraxxR#8801'
repository 'https://github.com/MiraxxR1/fivem-maintenance'
discord 'https://discord.gg/wJmnKQHTWD'
description 'This Lua script for FiveM allows you to set up a maintenance system for your server. '

server_scripts {
    "server/sv_maintenance.lua"
}
